[package]
name = "daino-fetch"
version.workspace = true
edition.workspace = true

[dependencies]
librustdash = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
