[package]
name = "daino-state"
version.workspace = true
edition.workspace = true

[dependencies]
daino-core = { workspace = true }
librustdash = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
heed = "0.20"
bincode = "1.3"

[dev-dependencies]
tempfile = "3.17"
