[package]
name = "dainod"
version.workspace = true
edition.workspace = true

[dependencies]
daino-core = { workspace = true }
daino-fetch = { workspace = true }
daino-serve = { workspace = true }
daino-state = { workspace = true }
librustdash = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
hex = { workspace = true }
